# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SidebarMenu' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod ‘Firebase’
	pod 'Firebase/Messaging'
pod 'BBBadgeBarButtonItem'

pod 'Fabric'
pod 'Crashlytics'

pod 'IQKeyboardManagerSwift'

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

pod 'JVFloatLabeledTextField'

  target 'SidebarMenuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
